sofia.countries =  [
    {"name":"Afghanistan","alpha-2":"AF","alpha-3":"AFG"},
    {"name":"Albania","alpha-2":"AL","alpha-3":"ALB"},
    {"name":"Algeria","alpha-2":"DZ","alpha-3":"DZA"},
    {"name":"Andorra","alpha-2":"AD","alpha-3":"AND"},
    {"name":"Angola","alpha-2":"AO","alpha-3":"AGO"},
    {"name":"Antigua and Barbuda","alpha-2":"AG","alpha-3":"ATG"},
    {"name":"Argentina","alpha-2":"AR","alpha-3":"ARG"},
    {"name":"Armenia","alpha-2":"AM","alpha-3":"ARM"},
    {"name":"Australia","alpha-2":"AU","alpha-3":"AUS"},
    {"name":"Austria","alpha-2":"AT","alpha-3":"AUT"},
    {"name":"Azerbaijan","alpha-2":"AZ","alpha-3":"AZE"},
    {"name":"The Bahamas","alpha-2":"BS","alpha-3":"BHS"},
    {"name":"Bahrain","alpha-2":"BH","alpha-3":"BHR"},
    {"name":"Bangladesh","alpha-2":"BD","alpha-3":"BGD"},
    {"name":"Barbados","alpha-2":"BB","alpha-3":"BRB"},
    {"name":"Belarus","alpha-2":"BY","alpha-3":"BLR"},
    {"name":"Belgium","alpha-2":"BE","alpha-3":"BEL"},
    {"name":"Belize","alpha-2":"BZ","alpha-3":"BLZ"},
    {"name":"Benin","alpha-2":"BJ","alpha-3":"BEN"},
    {"name":"Bhutan","alpha-2":"BT","alpha-3":"BTN"},
    {"name":"Bolivia","alpha-2":"BO","alpha-3":"BOL"},
    {"name":"Bosnia and Herzegovina","alpha-2":"BA","alpha-3":"BIH"},
    {"name":"Botswana","alpha-2":"BW","alpha-3":"BWA"},
    {"name":"Brazil","alpha-2":"BR","alpha-3":"BRA"},
    {"name":"Brunei","alpha-2":"BN","alpha-3":"BRN"},
    {"name":"Bulgaria","alpha-2":"BG","alpha-3":"BGR"},
    {"name":"Burkina Faso","alpha-2":"BF","alpha-3":"BFA"},
    {"name":"Burma","alpha-2":"MM","alpha-3":"MMR"},
    {"name":"Burundi","alpha-2":"BI","alpha-3":"BDI"},
    {"name":"Cabo Verde","alpha-2":"CV","alpha-3":"CPV"},
    {"name":"Cambodia","alpha-2":"KH","alpha-3":"KHM"},
    {"name":"Cameroon","alpha-2":"CM","alpha-3":"CMR"},
    {"name":"Canada","alpha-2":"CA","alpha-3":"CAN"},
    {"name":"Central African Republic","alpha-2":"CF","alpha-3":"CAF"},
    {"name":"Chad","alpha-2":"TD","alpha-3":"TCD"},
    {"name":"Chile","alpha-2":"CL","alpha-3":"CHL"},
    {"name":"China","alpha-2":"CN","alpha-3":"CHN"},
    {"name":"Colombia","alpha-2":"CO","alpha-3":"COL"},
    {"name":"Comoros","alpha-2":"KM","alpha-3":"COM"},
    {"name":"Congo (Brazzaville)","alpha-2":"CG","alpha-3":"COG"},
    {"name":"Congo (Kinshasa)","alpha-2":"CD","alpha-3":"COD"},
    {"name":"Costa Rica","alpha-2":"CR","alpha-3":"CRI"},
    {"name":"Côte d'Ivoire","alpha-2":"CI","alpha-3":"CIV"},
    {"name":"Croatia","alpha-2":"HR","alpha-3":"HRV"},
    {"name":"Cuba","alpha-2":"CU","alpha-3":"CUB"},
    {"name":"Cyprus","alpha-2":"CY","alpha-3":"CYP"},
    {"name":"Czechia","alpha-2":"CZ","alpha-3":"CZE"},
    {"name":"Denmark","alpha-2":"DK","alpha-3":"DNK"},
    {"name":"Djibouti","alpha-2":"DJ","alpha-3":"DJI"},
    {"name":"Dominica","alpha-2":"DM","alpha-3":"DMA"},
    {"name":"Dominican Republic","alpha-2":"DO","alpha-3":"DOM"},
    {"name":"Ecuador","alpha-2":"EC","alpha-3":"ECU"},
    {"name":"Egypt","alpha-2":"EG","alpha-3":"EGY"},
    {"name":"El Salvador","alpha-2":"SV","alpha-3":"SLV"},
    {"name":"Equatorial Guinea","alpha-2":"GQ","alpha-3":"GNQ"},
    {"name":"Eritrea","alpha-2":"ER","alpha-3":"ERI"},
    {"name":"Estonia","alpha-2":"EE","alpha-3":"EST"},
    {"name":"Ethiopia","alpha-2":"ET","alpha-3":"ETH"},
    {"name":"Fiji","alpha-2":"FJ","alpha-3":"FJI"},
    {"name":"Finland","alpha-2":"FI","alpha-3":"FIN"},
    {"name":"France","alpha-2":"FR","alpha-3":"FRA"},
    {"name":"Gabon","alpha-2":"GA","alpha-3":"GAB"},
    {"name":"The Gambia","alpha-2":"GM","alpha-3":"GMB"},
    {"name":"Georgia","alpha-2":"GE","alpha-3":"GEO"},
    {"name":"Germany","alpha-2":"DE","alpha-3":"DEU"},
    {"name":"Ghana","alpha-2":"GH","alpha-3":"GHA"},
    {"name":"Greece","alpha-2":"GR","alpha-3":"GRC"},
    {"name":"Grenada","alpha-2":"GD","alpha-3":"GRD"},
    {"name":"Guatemala","alpha-2":"GT","alpha-3":"GTM"},
    {"name":"Guinea","alpha-2":"GN","alpha-3":"GIN"},
    {"name":"Guinea-Bissau","alpha-2":"GW","alpha-3":"GNB"},
    {"name":"Guyana","alpha-2":"GY","alpha-3":"GUY"},
    {"name":"Haiti","alpha-2":"HT","alpha-3":"HTI"},
    {"name":"Honduras","alpha-2":"HN","alpha-3":"HND"},
    {"name":"Hungary","alpha-2":"HU","alpha-3":"HUN"},
    {"name":"Iceland","alpha-2":"IS","alpha-3":"ISL"},
    {"name":"India","alpha-2":"IN","alpha-3":"IND"},
    {"name":"Indonesia","alpha-2":"ID","alpha-3":"IDN"},
    {"name":"Iran","alpha-2":"IR","alpha-3":"IRN"},
    {"name":"Iraq","alpha-2":"IQ","alpha-3":"IRQ"},
    {"name":"Ireland","alpha-2":"IE","alpha-3":"IRL"},
    {"name":"Israel","alpha-2":"IL","alpha-3":"ISR"},
    {"name":"Italy","alpha-2":"IT","alpha-3":"ITA"},
    {"name":"Jamaica","alpha-2":"JM","alpha-3":"JAM"},
    {"name":"Japan","alpha-2":"JP","alpha-3":"JPN"},
    {"name":"Jordan","alpha-2":"JO","alpha-3":"JOR"},
    {"name":"Kazakhstan","alpha-2":"KZ","alpha-3":"KAZ"},
    {"name":"Kenya","alpha-2":"KE","alpha-3":"KEN"},
    {"name":"Kiribati","alpha-2":"KI","alpha-3":"KIR"},
    {"name":"North Korea","alpha-2":"KP","alpha-3":"PRK"},
    {"name":"South Korea","alpha-2":"KR","alpha-3":"KOR"},
    {"name":"Kosovo","alpha-2":"XK","alpha-3":"XKS"},
    {"name":"Kuwait","alpha-2":"KW","alpha-3":"KWT"},
    {"name":"Kyrgyzstan","alpha-2":"KG","alpha-3":"KGZ"},
    {"name":"Laos","alpha-2":"LA","alpha-3":"LAO"},
    {"name":"Latvia","alpha-2":"LV","alpha-3":"LVA"},
    {"name":"Lebanon","alpha-2":"LB","alpha-3":"LBN"},
    {"name":"Lesotho","alpha-2":"LS","alpha-3":"LSO"},
    {"name":"Liberia","alpha-2":"LR","alpha-3":"LBR"},
    {"name":"Libya","alpha-2":"LY","alpha-3":"LBY"},
    {"name":"Liechtenstein","alpha-2":"LI","alpha-3":"LIE"},
    {"name":"Lithuania","alpha-2":"LY","alpha-3":"LTU"},
    {"name":"Luxembourg","alpha-2":"LU","alpha-3":"LUX"},
    {"name":"Macedonia","alpha-2":"MK","alpha-3":"MKD"},
    {"name":"Madagascar","alpha-2":"MG","alpha-3":"MDG"},
    {"name":"Malawi","alpha-2":"MW","alpha-3":"MWI"},
    {"name":"Malaysia","alpha-2":"MY","alpha-3":"MYS"},
    {"name":"Maldives","alpha-2":"MV","alpha-3":"MDV"},
    {"name":"Mali","alpha-2":"ML","alpha-3":"MLI"},
    {"name":"Malta","alpha-2":"MT","alpha-3":"MLT"},
    {"name":"Marshall Islands","alpha-2":"MH","alpha-3":"MHL"},
    {"name":"Mauritania","alpha-2":"MR","alpha-3":"MRT"},
    {"name":"Mauritius","alpha-2":"MU","alpha-3":"MUS"},
    {"name":"Mexico","alpha-2":"MX","alpha-3":"MEX"},
    {"name":"Federated States of Micronesia","alpha-2":"FM","alpha-3":"FSM"},
    {"name":"Moldova","alpha-2":"MD","alpha-3":"MDA"},
    {"name":"Monaco","alpha-2":"MC","alpha-3":"MCO"},
    {"name":"Mongolia","alpha-2":"MN","alpha-3":"MNG"},
    {"name":"Montenegro","alpha-2":"ME","alpha-3":"MNE"},
    {"name":"Morocco","alpha-2":"MA","alpha-3":"MAR"},
    {"name":"Mozambique","alpha-2":"MZ","alpha-3":"MOZ"},
    {"name":"Namibia","alpha-2":"NA","alpha-3":"NAM"},
    {"name":"Nauru","alpha-2":"NR","alpha-3":"NRU"},
    {"name":"Nepal","alpha-2":"NP","alpha-3":"NPL"},
    {"name":"Netherlands","alpha-2":"NL","alpha-3":"NLD"},
    {"name":"New Zealand","alpha-2":"NZ","alpha-3":"NZL"},
    {"name":"Nicaragua","alpha-2":"NI","alpha-3":"NIC"},
    {"name":"Niger","alpha-2":"NE","alpha-3":"NER"},
    {"name":"Nigeria","alpha-2":"NG","alpha-3":"NGA"},
    {"name":"Norway","alpha-2":"NO","alpha-3":"NOR"},
    {"name":"Oman","alpha-2":"OM","alpha-3":"OMN"},
    {"name":"Pakistan","alpha-2":"PK","alpha-3":"PAK"},
    {"name":"Palau","alpha-2":"PW","alpha-3":"PLW"},
    {"name":"Panama","alpha-2":"PA","alpha-3":"PAN"},
    {"name":"Papua New Guinea","alpha-2":"PG","alpha-3":"PNG"},
    {"name":"Paraguay","alpha-2":"PY","alpha-3":"PRY"},
    {"name":"Peru","alpha-2":"PE","alpha-3":"PER"},
    {"name":"Philippines","alpha-2":"PH","alpha-3":"PHL"},
    {"name":"Poland","alpha-2":"PL","alpha-3":"POL"},
    {"name":"Portugal","alpha-2":"PT","alpha-3":"PRT"},
    {"name":"Qatar","alpha-2":"QA","alpha-3":"QAT"},
    {"name":"Romania","alpha-2":"RO","alpha-3":"ROU"},
    {"name":"Russia","alpha-2":"RU","alpha-3":"RUS"},
    {"name":"Rwanda","alpha-2":"RW","alpha-3":"RWA"},
    {"name":"Saint Kitts and Nevis","alpha-2":"KN","alpha-3":"KNA"},
    {"name":"Saint Lucia","alpha-2":"LC","alpha-3":"LCA"},
    {"name":"Saint Vincent and the Grenadines","alpha-2":"VC","alpha-3":"VCT"},
    {"name":"Samoa","alpha-2":"WS","alpha-3":"WSM"},
    {"name":"San Marino","alpha-2":"SM","alpha-3":"SMR"},
    {"name":"Sao Tome and Principe","alpha-2":"ST","alpha-3":"STP"},
    {"name":"Saudi Arabia","alpha-2":"SA","alpha-3":"SAU"},
    {"name":"Senegal","alpha-2":"SN","alpha-3":"SEN"},
    {"name":"Serbia","alpha-2":"RS","alpha-3":"SRB"},
    {"name":"Seychelles","alpha-2":"SC","alpha-3":"SYC"},
    {"name":"Sierra Leone","alpha-2":"SL","alpha-3":"SLE"},
    {"name":"Singapore","alpha-2":"SG","alpha-3":"SGP"},
    {"name":"Slovakia","alpha-2":"SK","alpha-3":"SVK"},
    {"name":"Slovenia","alpha-2":"SI","alpha-3":"SVN"},
    {"name":"Solomon Islands","alpha-2":"SB","alpha-3":"SLB"},
    {"name":"Somalia","alpha-2":"SO","alpha-3":"SOM"},
    {"name":"South Africa","alpha-2":"ZA","alpha-3":"ZAF"},
    {"name":"South Sudan","alpha-2":"SS","alpha-3":"SSD"},
    {"name":"Spain","alpha-2":"ES","alpha-3":"ESP"},
    {"name":"Sri Lanka","alpha-2":"LK","alpha-3":"LKA"},
    {"name":"Sudan","alpha-2":"SD","alpha-3":"SDN"},
    {"name":"Suriname","alpha-2":"SR","alpha-3":"SUR"},
    {"name":"Swaziland","alpha-2":"SZ","alpha-3":"SWZ"},
    {"name":"Sweden","alpha-2":"SE","alpha-3":"SWE"},
    {"name":"Switzerland","alpha-2":"CH","alpha-3":"CHE"},
    {"name":"Syria","alpha-2":"SY","alpha-3":"SYR"},
    {"name":"Tajikistan","alpha-2":"TJ","alpha-3":"TJK"},
    {"name":"Tanzania","alpha-2":"TZ","alpha-3":"TZA"},
    {"name":"Thailand","alpha-2":"TH","alpha-3":"THA"},
    {"name":"Timor-Leste","alpha-2":"TL","alpha-3":"TLS"},
    {"name":"Togo","alpha-2":"TG","alpha-3":"TGO"},
    {"name":"Tonga","alpha-2":"TO","alpha-3":"TON"},
    {"name":"Trinidad and Tobago","alpha-2":"TT","alpha-3":"TTO"},
    {"name":"Tunisia","alpha-2":"TN","alpha-3":"TUN"},
    {"name":"Turkey","alpha-2":"TR","alpha-3":"TUR"},
    {"name":"Turkmenistan","alpha-2":"TM","alpha-3":"TKM"},
    {"name":"Tuvalu","alpha-2":"TV","alpha-3":"TUV"},
    {"name":"Uganda","alpha-2":"UG","alpha-3":"UGA"},
    {"name":"Ukraine","alpha-2":"UA","alpha-3":"UKR"},
    {"name":"United Arab Emirates","alpha-2":"AE","alpha-3":"ARE"},
    {"name":"United Kingdom","alpha-2":"GB","alpha-3":"GBR"},
    {"name":"United States","alpha-2":"US","alpha-3":"USA"},
    {"name":"Uruguay","alpha-2":"UY","alpha-3":"URY"},
    {"name":"Uzbekistan","alpha-2":"UZ","alpha-3":"UZB"},
    {"name":"Vanuatu","alpha-2":"VU","alpha-3":"VUT"},
    {"name":"Venezuela","alpha-2":"VE","alpha-3":"VEN"},
    {"name":"Vietnam","alpha-2":"VN","alpha-3":"VNM"},
    {"name":"Yemen","alpha-2":"YE","alpha-3":"YEM"},
    {"name":"Zambia","alpha-2":"ZM","alpha-3":"ZMB"}
];